config/routes.rb
Rails.application.routes.draw do

  get 'interventions/get_site'
  get 'interventions/get_mission'
  resources :interventions do
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}

  root 'interventions#new'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :trackable, :validatable #:recoverable, :rememberable,
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :sites
end

app/models/intervention.rb
class Intervention < ActiveRecord::Base
  belongs_to :mission
  belongs_to :user
end

app/models/mission.rb
class Mission < ActiveRecord::Base
  belongs_to :site
  has_many :interventions
end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :client
  has_many :missions
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable#,
        #  :trackable, :validatable #:recoverable, :rememberable,

  has_many :interventions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :redirect_to_sign_in
  before_filter :crypt_password_new_user

  private

  def crypt_password_new_user
    if request.fullpath == "/admin/users"
      if params
        if params[:user]
          if params[:user][:encrypted_password]
            params[:user][:encrypted_password] = BCrypt::Password.create(params[:user][:encrypted_password])
          end
        end
      end
    end
  end

  def redirect_to_sign_in # TODO don't work because can go anywhere
    if request.fullpath == "/" && !current_user
      redirect_to "/users/sign_in"
    end
  end

  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/interventions_controller.rb
class InterventionsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @interventions = Intervention.where(user_id: current_user.id)
  end

  def new
    @intervention = Intervention.new
    @clients = Client.all.order('name ASC')
  end

  def create
    i = params[:intervention]
    i[:user_id] = current_user.id
    i[:datetime] = Date.parse(i[:datetime])
    i[:nb_hour] = i[:nb_hour_h].to_f + i[:nb_hour_m].to_f

    @intervention = Intervention.new(inter_params)
    puts @intervention.inspect
    respond_to do |format|
      if @intervention.save
        format.html { redirect_to(new_intervention_url, :notice => 'L\'intervention a bien été enregistrée' ) }
      else
       format.html { redirect_to(new_intervention_url , :alert => 'Une erreur c\'est produite lors de l\'enregistrement') }
      end
    end
  end

  def get_site
    @sites = Site.where(client_id: params[:client_id]).order('name ASC')
    render :json => @sites
  end

  def get_mission
    @missions = Mission.where(site_id: params[:site_id]).order('name ASC')
    render :json => @missions
  end

  private

  def inter_params
    params.require(:intervention).permit(:datetime, :nb_hour, :panier, :zone, :comment, :mission_id, :user_id)
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    flash[:info] = 'Registrations are not open yet, but please check back soon'
    redirect_to root_path
  end

  def new
    flash[:info] = 'Registrations are not open yet, but please check back soon'
    redirect_to root_path
  end

  def edit
    flash[:info] = 'Registrations are not open yet, but please check back soon'
    redirect_to root_path
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interventions_helper.rb
module InterventionsHelper
end

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default navbar-inverse" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Fiche Horaire", defined?(root_path) ? root_path : "#", class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li><%= link_to "créer une intervention", new_intervention_path %></li>
          <li><%= link_to "voir ces interventions", interventions_path %></li>
          <!-- <li class="dropdown"> -->
            <!-- <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a> -->
            <!-- <ul class="dropdown-menu"> -->
              <!-- <li><%= link_to "Edit Account", edit_user_registration_path %></li> -->
              <!-- <li class="divider"></li> -->
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            <!-- </ul> -->
          <!-- </li> -->
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/interventions/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>mission</th>
      <th>date</th>
      <th>nombre d'heure</th>
      <th>panier</th>
      <th>zone</th>
      <th>commentaire</th>
    </tr>
  </thead>
  <tbody>
    <% @interventions.each do |i| %>
      <tr>
        <td><%= Mission.find(i.mission_id).name %></td>
        <td><%= i.datetime %></td>
        <td><%= i.nb_hour %></td>
        <td><%= i.panier %></td>
        <td><%= i.zone %></td>
        <td><%= i.comment %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/interventions/new.html.erb
<%= form_for @intervention, :validate => true, html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <label class="control-label col-sm-2">date</label>
    <div class="col-sm-6">
      <input type="text" data-provide='datepicker' data-date-format="dd-mm-yyyy" class="form-control" name="intervention[datetime]" value="<%= Time.now.strftime("%d-%m-%Y") %>">
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2" for="exampleInputEmail1">client</label>
    <div class="col-sm-6">
      <select class="form-control" id="select_client">
        <option value="">Choisissez un client</option>
        <% @clients.each do |c| %>
          <option value="<%= c.id %>"><%= c.name %></option>
        <% end %>
      </select>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2">site</label>
    <div class="col-sm-6">
      <select class="form-control" id="select_site">
      </select>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2">mission</label>
    <div class="col-sm-6">
      <select class="form-control" id="select_mission" name="intervention[mission_id]">
      </select>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2">Nombre d'heure</label>
    <div class="col-sm-6">
      <!-- <input type="number" class="form-control" placeholder="ex: 3.5" min="0" step="any" name="intervention[nb_hour_h]"> -->

      <select class="form-control col-sm-6" name="intervention[nb_hour_h]">
        <option>0</option>
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option>5</option>
        <option>6</option>
        <option>7</option>
        <option>8</option>
        <option>9</option>
        <option>10</option>
        <option>11</option>
        <option>12</option>
        <option>13</option>
        <option>14</option>
      </select>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-sm-2">Nombre de minute</label>
    <div class="col-sm-6">
      <select class="form-control" name="intervention[nb_hour_m]">
        <option>0</option>
        <option>0.25</option>
        <option>0.50</option>
        <option>0.75</option>
      </select>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2">panier</label>
    <div class="col-sm-6">
      <select class="form-control" name="intervention[panier]">
        <option>0</option>
        <option>1</option>
        <option>2</option>
      </select>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2">zone</label>
    <div class="col-sm-6">
      <select class="form-control" name="intervention[zone]">
        <option>0</option>
        <option>1</option>
        <option>2</option>
        <option>3</option>
        <option>4</option>
        <option>5</option>
        <option>6</option>
      </select>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-sm-2">Commentaire</label>
    <div class="col-sm-6">
      <textarea class="form-control" rows="3" name="intervention[comment]"></textarea>
    </div>
  </div>

  <div class="col-sm-offset-2 col-sm-10">
    <button type="submit" class="btn btn-default">Submit</button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fiche Horaire</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'active_admin' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
  </head>
  <body>
    <%= render partial: "elements/navbar" %>
    <%= bootstrap_flash %>

    <div class="container">
      <div class="starter-template">
        <%= yield %>
      </div>
    </div>

  </body>
</html>